### ISSUE TITLE
meta-lmp dependency integration:  WireGuard

### ISSUE THREAD

**Issue by illibrium** [toradex/meta-toradex-torizon#11]
Reference issue: TOR-2247  (https://developer-archives.toradex.com/software/torizon/release-details?issue=TOR-2247&key=TOR-2247)

I have a project that worked well at TorizonCore version 5.2.0 with a "meta-lmp" dependency, mainly for it's WireGuard functionality.

While trying to update this to 5.7.1 I've come across several patch conflicts that are introduced by meta-lmp, even when using the latest "dunfell" version available (https://github.com/foundriesio/meta-lmp/tree/dunfell/meta-lmp-base).

I also read that the dependency of meta-lmp was supposed to be removed in version 5.7.0 as a "feature" and that it's features would be pushed to this repo "meta-toradex-torizon"  (Ref: https://community.toradex.com/t/torizoncore-5-7-0-quarterly-release/17576).

Can the WireGuard installation and config from "meta-lmp" be transferred over to "meta-toradex-torizon" so I can really break dependence on it?   The impact of issue TOR-2247 is "high" for me if it doesn't come from somewhere.

Does this already cover WireGuard at a level higher than this (making my request obsolete?)
https://github.com/openembedded/meta-openembedded/tree/master/meta-networking/recipes-kernel/wireguard

**Comment by sergioprado** [comment]
We do ship WireGuard installed by default on TorizonCore 5.7.1. Any specific reason you need the one from meta-lmp?

**Comment by illibrium** [comment]
As long as it is still included, then I don't think there's actually any issue.  I just need a better way to stay on top of how evolving changes in 16 different main repos in my manifest effect the net capabilities in my build.  For example, it could be a while before I realize the impact, if any, of removing meta-lmp since it had a ton of dependencies and configuration that I may be depending on.  On the other hand, I needed to remove it for my 5.7.1 build to complete without patching conflicts that broke the updated build.

**Comment by sergioprado** [comment]
I would suggest you to base your manifest on top of ours, since all of these dependencies are already handled. There are tags there for all major (quarterly) releases.

**Comment by microhobby** [comment]
@leograba @sergioprado I think that should be good to also tag the major and quarterly releases here

**Comment by leograba** [comment]
@microhobby with the tags in the manifest, all meta layers refs can be found there. Do you have anything specific in mind?

**Comment by microhobby** [comment]
@leograba yes, but sometimes I use here GitHub UI as reference for my work, and then I need to go to other project find the right tag then check the hash, come back here find the hash ...

This is more productive in the CLI, but using the GitHub is an annoying task. Should be good to have here the tags because it's make quicker to check the commits from the version...

**Comment by leograba** [comment]
Since the topic changed here from WireGuard support to other topics, @microhobby @illibrium please open new separate requests if you want to continue discussing these, and reference the current issue.

Closing this one since WireGuard is supported and will continue to be for the foreseeable future.
