### ISSUE TITLE
Bookworm containers for Chromium and Cog

### ISSUE THREAD

**Issue by escherstair** [toradex/meta-toradex-torizon#12]
I know the task is already on the roadmap (and maybe in progress), but I open this issue so that it's easier for the customer searching about the status.
In a [recent commit](https://github.com/toradex/meta-toradex-torizon/commit/cd8512025a42981b1a0bd77969f91648dddb0dca) the browsers containers have been reverted to bullseye, waiting for bookworm containers release.
Close this issue when bookworm containers for Chromium and Cog will be released.

**Comment by leonheld** [comment]
Bumped in https://github.com/toradex/meta-toradex-torizon/commit/8ca42437dff3ca3c7e5084e3dad87bb57e4af9f8.
